/**
 * Storage provider seam (Stage 6, Part 6) -- Cloudinary is the first and only real implementation
 * today, but every consumer (upload actions, Demo Library UI) talks to this interface, never to
 * `cloudinary-provider.ts` directly, so a second provider (S3, R2, Drive) is a new file that
 * implements this shape plus a switch in `getActiveStorageProvider()` -- no changes anywhere else.
 */

export interface UploadSignatureParams {
  /** Logical folder path, e.g. "demo-library". Providers may ignore this if not applicable. */
  folder: string;
  /** Stable id this upload should be stored under -- generated by the caller (demo id), never
   *  provider-generated, so the CRM always knows the exact URL/public id before the upload
   *  finishes. */
  publicId: string;
  /** Restricts what the signed upload accepts -- "video" today, kept generic for future asset
   *  types (thumbnail-only re-uploads, etc.). */
  resourceType: "video" | "image" | "auto";
}

/**
 * Everything a browser needs to upload directly to the provider without ever seeing a secret.
 * Shaped close to Cloudinary's own signed-upload contract since that's the only real
 * implementation, but deliberately provider-agnostic in field names.
 */
export interface UploadSignature {
  provider: string;
  uploadUrl: string;
  fields: Record<string, string>;
}

export interface StorageUsage {
  storageBytes: number | null;
  credits: number | null;
  fetchedAt: string;
}

export interface StorageHealth {
  provider: string;
  configured: boolean;
  connected: boolean;
  usage: StorageUsage | null;
  error?: string;
}

export interface StorageProvider {
  id: string;
  /** True once the required env vars are present -- never assumes connectivity, just presence. */
  isConfigured(): boolean;
  /** Server-side: builds a signature the browser uses to upload directly to the provider. Throws
   *  if not configured -- callers must check isConfigured() first (see demo-uploads.ts). */
  createUploadSignature(params: UploadSignatureParams): UploadSignature;
  /** Given a delivery URL this provider issued, derive a poster-frame thumbnail URL using the
   *  provider's own on-the-fly transform -- never a guess, returns null if the URL isn't
   *  recognizably this provider's. */
  deriveThumbnailUrl(deliveryUrl: string): string | null;
  /** Given a delivery URL, derive a forced-download variant -- null if not derivable. */
  deriveDownloadUrl(deliveryUrl: string): string | null;
  /** Live connectivity + account usage check (Part 6 "Storage Health"). Never throws -- failures
   *  are reported in the returned health object, not as exceptions, since this backs a dashboard
   *  panel that must render even when the provider is unreachable. */
  getHealth(): Promise<StorageHealth>;
}
