export type LeadStatus =
  | "Staged"
  | "New"
  | "Sent"
  | "Contacted"
  | "Interested"
  | "Not Interested"
  | "Meeting Booked"
  | "Customer"
  | "Failed"
  | "Unsubscribed"
  | "Spam"
  | "Needs Review"
  /** Hard-bounced (Stage 5, Part F) -- n8n's Prepare Leads For Processing STOP_STATUSES already
   *  treats the literal string "bounced" as terminal, so setting this status alone suppresses
   *  future sends with no workflow change required. */
  | "Bounced";

export const LEAD_STATUSES: LeadStatus[] = [
  "Staged",
  "New",
  "Sent",
  "Contacted",
  "Interested",
  "Not Interested",
  "Meeting Booked",
  "Customer",
  "Failed",
  "Unsubscribed",
  "Spam",
  "Needs Review",
  "Bounced",
];

/** Pipeline-specific grouping used by the Kanban board (a subset/remap of LeadStatus). */
export type PipelineStage =
  | "New"
  | "Contacted"
  | "Interested"
  | "Meeting Booked"
  | "Customer"
  | "Failed"
  | "Unsubscribed";

export const PIPELINE_STAGES: PipelineStage[] = [
  "New",
  "Contacted",
  "Interested",
  "Meeting Booked",
  "Customer",
  "Failed",
  "Unsubscribed",
];

export interface Lead {
  /** Primary key across the whole app -- matches the n8n workflow's matching column. */
  email: string;
  name: string;
  company: string;
  website?: string;
  industry?: string;
  businessType?: string;
  leadGenerationType?: string;
  phone?: string;
  country?: string;
  status: LeadStatus;
  lastContact: string | null;
  followUpCount: number;
  lastEmailSubject?: string;
  lastEmailDate: string | null;
  serviceOffered?: string;
  aiSummary?: string;
  demoVideoAttached: boolean;
  demoVideoName?: string;
  subjectVariant?: string;
  alternativeSubject?: string;
  /** AI's per-lead suggestion -- informational only since Change 3; never gates whether a demo
   *  is actually attached (see demoVideoAttached, which reflects the real, campaign-resolved
   *  decision from resolveCampaignDemo). */
  demoRecommended: boolean;
  demoType?: string;
  demoWatchUrl?: string;
  demoDownloadUrl?: string;
  /** Canonical Demo Library id of the demo actually resolved for this send, if any. */
  demoId?: string;
  /** True only after the email that carried this demo actually sent successfully -- never set
   *  merely because a demo was recommended or resolved (see n8n's Log Email Sent, success branch
   *  only). Distinct from demoVideoAttached (whether the *most recent prepared* email included a
   *  demo) -- this is the durable, actual-send outcome. */
  demoSent?: boolean;
  demoSentAt?: string | null;
  /** Why this demo (or no demo) was selected -- one of demo-match.ts's DemoMatchReason values,
   *  e.g. "exact-id", "auto-service-industry", "fallback-demo", "no-match". */
  demoMatchReason?: string;
  emailStyle?: string;
  /** 0-100, null when the AI has not scored this lead yet. */
  confidence: number | null;
  /** Stable Campaign ID (Campaigns sheet's ID column) this lead is assigned to (Stage 6, Part 4:
   *  every lead created through the CRM must carry one). "" is the explicit sentinel for legacy
   *  rows written before this was enforced -- never inferred from industry/business type/status. */
  campaignId: string;
  /** Denormalized campaign name at import/create time -- display only, campaignId stays the
   *  source of truth for matching. */
  campaignName?: string;
  /** Stable identifier for this lead row -- blank for rows created before this column existed
   *  (never inferred from row position). */
  leadId?: string;
  /** Free-text location string (e.g. "Austin, TX") -- distinct from Country. */
  location?: string;
  /** The service/niche this lead was targeted for, as opposed to serviceOffered (what was
   *  actually pitched during outreach). */
  targetService?: string;
  /** Where this lead came from -- e.g. "Manual", "Import", "API". Blank for rows written before
   *  this column existed. */
  source?: string;
  /** When this row was created -- set by the create action; blank for legacy rows. */
  createdAt?: string;
  /** Stage 5 tracking identifiers -- both set to the same opaque per-send token generated by n8n's
   *  Prepare Final Email node (see analytics-event.ts doc comment on why they're collapsed for
   *  this first implementation). Blank for leads that predate Stage 5 or haven't been sent yet. */
  messageId?: string;
  trackingToken?: string;
  /** n8n execution id that produced this send -- audit/debug only, never displayed as proof of
   *  delivery. */
  n8nExecutionId?: string;
  openCount?: number;
  firstOpenedAt?: string | null;
  lastOpenedAt?: string | null;
  clickCount?: number;
  firstClickedAt?: string | null;
  lastClickedAt?: string | null;
  /** "Hard" | "Soft" | undefined -- set only by real DSN/bounce evidence, never guessed. */
  bounceType?: string;
  bouncedAt?: string | null;
  complaintAt?: string | null;
  /** Free-text reason a lead was suppressed (bounce/unsubscribe/complaint) -- audit trail, not a
   *  gate itself (Status is the actual gate n8n's STOP_STATUSES checks). */
  suppressedReason?: string;
  /** Additive "Is Test" column -- explicit admin-set marker, never inferred from name or
   *  content. Missing/blank on any existing row (including every row written before this column
   *  existed) reads as `false` -- see normalizeLead. Set at creation (inherited from the assigned
   *  campaign's own isTest flag) or explicitly by an admin action. */
  isTest: boolean;
  /** Row position in the source sheet, used for targeted updates. Absent in mock mode. */
  rowNumber?: number;
}

export interface LeadNote {
  id: string;
  leadEmail: string;
  author: string;
  body: string;
  createdAt: string;
}
